// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelMinimalAPI.DbContexts;

#nullable disable

namespace TravelMinimalAPI.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    partial class TravelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4");

            modelBuilder.Entity("ActivityDestination", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivitiesId", "DestinationsId");

                    b.HasIndex("DestinationsId");

                    b.ToTable("ActivityDestination");

                    b.HasData(
                        new
                        {
                            ActivitiesId = 1,
                            DestinationsId = 1
                        },
                        new
                        {
                            ActivitiesId = 2,
                            DestinationsId = 1
                        },
                        new
                        {
                            ActivitiesId = 4,
                            DestinationsId = 1
                        },
                        new
                        {
                            ActivitiesId = 6,
                            DestinationsId = 1
                        },
                        new
                        {
                            ActivitiesId = 1,
                            DestinationsId = 2
                        },
                        new
                        {
                            ActivitiesId = 2,
                            DestinationsId = 2
                        },
                        new
                        {
                            ActivitiesId = 3,
                            DestinationsId = 2
                        },
                        new
                        {
                            ActivitiesId = 4,
                            DestinationsId = 2
                        },
                        new
                        {
                            ActivitiesId = 3,
                            DestinationsId = 3
                        },
                        new
                        {
                            ActivitiesId = 5,
                            DestinationsId = 3
                        },
                        new
                        {
                            ActivitiesId = 2,
                            DestinationsId = 4
                        },
                        new
                        {
                            ActivitiesId = 3,
                            DestinationsId = 4
                        },
                        new
                        {
                            ActivitiesId = 4,
                            DestinationsId = 4
                        },
                        new
                        {
                            ActivitiesId = 5,
                            DestinationsId = 4
                        });
                });

            modelBuilder.Entity("TravelMinimalAPI.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nice weather"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Good food"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Castles"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nice People"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Good beer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Good wine"
                        });
                });

            modelBuilder.Entity("TravelMinimalAPI.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Poland"
                        });
                });

            modelBuilder.Entity("ActivityDestination", b =>
                {
                    b.HasOne("TravelMinimalAPI.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelMinimalAPI.Entities.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
